services:
  traefik:
    command:
      - "--providers.docker"
      - "--entryPoints.web.address=:80"

  nginx:
    labels:
      # Serve nginx via HTTP
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.rule=Host(`${DOMAIN}`)"
