version: "3.9"

services:
  # Nginx container with RTMP support which is exposed to the internet.
  nginx:
    image: alfg/nginx-rtmp:latest
    init: true
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - nginx-logs:/var/log/nginx
      # - ./overlay/nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - "${NGINX_CONF}:/etc/nginx/nginx.conf.template"

  # Prometheus Exporter to count HLS viewers, nginx_hls_viewer.
  nginx-hls-prometheus-exporter:
    depends_on:
      - nginx
    build: ./container/nginx-hls-prometheus-exporter/
    ports:
      - "9101:9101"
    volumes:
      - nginx-logs:/var/log/nginx

  # Prometheus Exporter to count RTMP viewers, nginx_rtmp_viewer.
  nginx-rtmp-prometheus-exporter:
    depends_on:
      - nginx
    build: ./container/nginx-rtmp-prometheus-exporter/
    ports:
      - "9102:9102"

  # BBB Live Streaming connects to the remote BBB session, starts a recording
  # and streams to Nginx via RTMP.
  bbb-streamer:
    depends_on:
      - bbb-streamer-mount-perm
      - nginx
    build: ./container/bbb-streamer/
    init: true
    shm_size: '2gb'
    environment:
      - BBB_STREAM_URL=rtmp://nginx:1935/stream/test
      - BBB_RESOLUTION=1280x720
      - BBB_DOWNLOAD_MEETING=true
      - TZ=Europe/Berlin
      - DEBUG=1
    env_file: .env
    volumes:
      - "${VIDEO_MNT}:/video"

  # This container fixes the user permissions for the /video mount point used in
  # bbb-streamer to store downloadable video records.
  # https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/137
  bbb-streamer-mount-perm:
    build: ./container/bbb-streamer-mount-perm/
    volumes:
      - "${VIDEO_MNT}:/video"

volumes:
  # Shared nginx logs between Nginx and the HLS Prometheus exporter.
  nginx-logs:
