version: "3.9"
services:
  nginx:
    image: alfg/nginx-rtmp:latest
    init: true
    ports:
      - "80:80"
      - "1935:1935"

  # This container fixes the user permissions for the /video mount point used in
  # bbb-streamer to store downloadable video records.
  # https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/137
  bbb-streamer-mount-perm:
    build: ./container/bbb-streamer-mount-perm/
    volumes:
      - /var/videodata:/video

  bbb-streamer:
    depends_on:
      - bbb-streamer-mount-perm
      - nginx
    build: ./container/bbb-streamer/
    init: true
    shm_size: '2gb'
    environment:
      - BBB_STREAM_URL=rtmp://nginx:1935/stream/test
      - BBB_RESOLUTION=1280x720
      - BBB_DOWNLOAD_MEETING=true
      - TZ=Europe/Berlin
      - DEBUG=1
    env_file: .env
    volumes:
      - /var/videodata:/video
